apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: clamav
spec:
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      #nodeSelector:
      #  type: infra
      containers:
        - name: clamav
          image: clamav:v1
          env:
          - name: CLAMAV_VOLUME
            value: /srv
          livenessProbe:
            exec:
              command: ["/usr/bin/check_clamd.sh"]
            initialDelaySeconds: 15
            timeoutSeconds: 3
          securityContext:
            privileged: true
          volumeMounts:
            - name: clamav-persistent-storage
              mountPath: /srv
      restartPolicy: Always
      volumes:
        - name: clamav-persistent-storage
          hostPath:
            path: /tmp/clamav-volume
