# Requires: oadm policy add-scc-to-user privileged -z default
# It adds system:serviceaccounts:<namespace>:default SA to the privileged SCC users so they have access
# to run with privileged settings
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: clamav
spec:
  template:
    metadata:
      labels:
        name: clamav
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #   type: infra
      containers:
        - name: clamav
          image: clamav:v1
          env:
          - name: CLAMAV_VOLUME
            value: /srv
          livenessProbe:
            exec:
              command: ["/usr/bin/check_clamd.sh"]
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 0.15
          volumeMounts:
            - name: clamav-persistent-storage
              mountPath: /srv
      restartPolicy: Always
      volumes:
        - name: clamav-persistent-storage
          hostPath:
            path: /tmp/clamav-volume
